package com.bt.metb.aggregator.constants;

public class DaoConstants {

    private DaoConstants() {
    }

    public static final int ERRORCODE_UNIQUE_CONSTRAINT_VIOLATED = 00001;

    public static final String ORMETB_DATASOURCE = "ormetbds";

    public static final String UPDATE_AGG_STATUS_WITH_REQUEST_XML = "UPDATE TASKDETAILS SET LASTUPDATED=?, AGG_NAME =?, REQUEST_STATUS=? ,CORRELATION_ID= ?, AGG_RETRY_COUNT=0 WHERE MET_REF_NUMBER=?";
    public static final String SELECT_ROW_EXISTS = "SELECT COUNT(*) FROM TASKDETAILS_AGG_MESSAGE WHERE MET_REF_NUMBER=?";
    public static final String INSERT_TASKDETAILS_AGG_MESSAGE = "INSERT INTO TASKDETAILS_AGG_MESSAGE(MET_REF_NUMBER, TYPE_OF_AGGREGATION, MESSAGE_TYPE, AGG_XML, INSERTED_DATETIME, AGGREGATION_ID) values (?, ?, ?, ?, ?, AGGREGATION_ID_SEQ.nextval)";

    public static final String UPDATE_AGG_MESSAGE_XML_NULL = "UPDATE TASKDETAILS_AGG_MESSAGE SET AGG_XML= NULL WHERE MET_REF_NUMBER=? AND TYPE_OF_AGGREGATION =?";

    public static final String SELECT_AGGREGATION_RESPONSE_DETAIL_OBJ_QUERY = "SELECT REQUEST_STATUS,TASK_REF_NUMBER,MET_REF_NUMBER,PRODUCT,AGG_NAME,TASKCATEGORY,LASTUPDATED,LATEST_OPERATION,E2EDATA,REPLYTO,LOB,SMNT_RETRY_COUNT,SOURCEADDRESS,SOURCEINSTANCEID FROM TASKDETAILS WHERE CORRELATION_ID = ?";

    public static final String SELECT_REQUEST_DETAILS = "SELECT TASK_REF_NUMBER, E2EDATA, PRODUCT, REPLYTO,TASKCATEGORY, LOB, REQUEST_XML, SMNT_RETRY_COUNT,SOURCEADDRESS,SOURCEINSTANCEID FROM TASKDETAILS WHERE MET_REF_NUMBER=?";

    public static final String SELECT_REQUEST_XML_FOR_TASK = "Select REQUEST_XML from TASKDETAILS_REQUEST_MESSAGE where MET_REF_NUMBER = ?";

    public static final String INSERT_AGGREGATION_LOG = "INSERT INTO AGGREGATION_LOG(MET_REF_NUMBER, ERROR_CODE, ERROR_DESCRIPTION,ERROR_TEXT) VALUES (?,?,?,?)";

    public static final String INSERT_HASHDATA = "INSERT INTO AGGREGATION_DATA(MET_REF_NUMBER, AGGREGATION, KEY, VALUE) VALUES (?,?,?,?)";

    public static final String UPDATE_STUCK_RETRY_REQUEST = "UPDATE TASKDETAILS SET LASTUPDATED=?, AGG_RETRY_COUNT =?, RETRY_STATUS=NULL,REQUEST_STATUS = ?,SERVER_NAME =NULL WHERE RETRY_STATUS IS NOT NULL AND MET_REF_NUMBER=?";

    public static final String SELECT_AGGREGATION_DATA_FOR_RESPONSE = "SELECT KEY,VALUE FROM AGGREGATION_DATA WHERE MET_REF_NUMBER=? AND AGGREGATION=?";

    public static final String UPDATE_RESPONSE_DATA_QUERY = "UPDATE TASKDETAILS SET RESPONSESTATUS = ?,LASTUPDATED=SYSDATE WHERE MET_REF_NUMBER = ?";

    public static final String SELECT_HASHDATA_QUERY = "SELECT AGGREGATION_DATA.MET_REF_NUMBER, AGGREGATION, KEY, VALUE FROM AGGREGATION_DATA, TASKDETAILS WHERE AGGREGATION_DATA.MET_REF_NUMBER = TASKDETAILS.MET_REF_NUMBER AND TASK_REF_NUMBER = ? AND SOURCEINSTANCEID = ? AND SOURCEADDRESS = ?";

    public static final String DELETE_HASHDATA_QUERY = "DELETE AGGREGATION_DATA WHERE MET_REF_NUMBER = ?";

    public static final String UPDATE_TECHNICAL_FAILURE_RESPONSE_QUERY = "UPDATE TASKDETAILS SET RESPONSESTATUS = ?,LASTUPDATED=SYSDATE WHERE TASK_REF_NUMBER = ? AND SOURCEINSTANCEID = ? AND SOURCEADDRESS = ?";

    public static final String UPDATE_TASKDETAILS_DATA_QUERY = "UPDATE TASKDETAILS SET REQUEST_STATUS = ?,RETRY_STATUS = ?, SERVER_NAME = ? , LASTUPDATED  = ?  WHERE MET_REF_NUMBER = ?";

    public static final String UPDATE_STUCK_REQUEST_TASKDETAILS_DATA_QUERY = "UPDATE TASKDETAILS SET REQUEST_STATUS = NULL,RETRY_STATUS = NULL, SERVER_NAME = NULL ,CORRELATION_ID = NULL, AGG_RETRY_COUNT = 0, AGG_NAME = NULL,  LASTUPDATED  = ?  WHERE RETRY_STATUS IS NOT NULL AND MET_REF_NUMBER = ?";

    public static final String UPDATE_TASKDETAILS_REQUESTSTATUS_QUERY = "UPDATE TASKDETAILS SET RETRY_STATUS=NULL,SERVER_NAME =NULL,REQUEST_STATUS = ?, LASTUPDATED  = ? WHERE MET_REF_NUMBER = ?";

    public static final String UPDATE_TASKDETAILS_REQUESTSTATUSITR_QUERY = "UPDATE TASKDETAILS SET REQUEST_STATUS = ?, LASTUPDATED  = ? WHERE MET_REF_NUMBER = ? AND REQUEST_STATUS= ? ";

    public static final String UPDATE_SERVERLOOKUP_RECENT_DATETIME_QUERY = "UPDATE SERVERLOOKUP SET STATUS = 'VALID', LASTPROCESSDATE = ? WHERE SERVERNAME = ? ";

    public static final String DELETE_AGGREGATION_SPECIFIC_QUERY = "DELETE AGGREGATION_DATA WHERE MET_REF_NUMBER = ? AND AGGREGATION = ?";

    public static final String UPDATE_STUCK_REQCONT_REQUEST = "UPDATE TASKDETAILS SET LASTUPDATED=?, RETRY_STATUS=NULL, REQUEST_STATUS= ?,SERVER_NAME =NULL WHERE RETRY_STATUS IS NOT NULL AND MET_REF_NUMBER=?";

    /*
 * Constants Used in DAO.java
 *
 * */
    public static final String MET_REF_NUMBER = "MET_REF_NUMBER";
    public static final String TASK_REF_NUMBER = "TASK_REF_NUMBER";
    public static final String REQUEST_STATUS = "REQUEST_STATUS";
    public static final String PRODUCT = "PRODUCT";
    public static final String AGG_NAME = "AGG_NAME";
    public static final String TASK_CATEGORY = "TASKCATEGORY";
    public static final String LASTUPDATED = "LASTUPDATED";
    public static final String LATEST_OPERATION = "LATEST_OPERATION";
    public static final String E2E_DATA = "E2EDATA";
    public static final String REPLY_TO = "REPLYTO";
    public static final String LOB = "LOB";
    public static final String SMNT_RETRY_COUNT = "SMNT_RETRY_COUNT";
    public static final String SOURCE_ADDRESS = "SOURCEADDRESS";
    public static final String SOURCE_INSTANCE_ID = "SOURCEINSTANCEID";
    public static final String REQUEST_XML = "REQUEST_XML";
}
